project:
  type: website
  output-dir: docs # to publish website on GithubPages
# --- By default, all valid Quarto input files (.qmd, .ipynb, .md, .Rmd)
#  will be rendered (NO .file, _dir/)
  render:
    - "*.qmd"
    - "!secret/"

execute:
  freeze: auto  # Re-render only when source changes

website:
  title: "Idee per Pavia"
  site-url: https://lulliter.github.io/ideeperpavia #"https://github.com/Lulliter/ideexpavia"
  favicon: images/icons8-walking-bridge-32.png
  search: false # no magnifier on navbar

  page-footer:
    left: |
      {{< fa regular fa copyright >}} Pastorale Sociale del Lavoro 2024
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)
    background: "#E4D3D1"

  navbar:
    pinned: true
    background: "#77221b" # "#72aed8" # "#b78a92" #  "#0084e6" "#EE6A24"
    right:
      - text: "Proposte"
        icon: house-fill # https://icons.getbootstrap.com/?q=home
        href: index.qmd
      # - text: "Notes"
      #   icon: archive-fill #  archive-fill # https://icons.getbootstrap.com/?q=home
      #   href: 01_pnrr.qmd
      - text: "Chi siamo"
        icon: people-fill # https://icons.getbootstrap.com/?q=home
        href: noi.qmd

format:
  html:
    toc: true
    toc-location: "left"
    code-link: true
    # anchor-sections: true
    # fig-cap-location: margin
    # reference-location: margin
    footnotes-hover: true
    fontsize: 1em
    theme: theme/Lulas_theme.scss
    # css: theme/styles.css
    ##----- code highlighting style
    highlight-style: monokai # atom-one # github # dracula
    mainfont: "Lato"
    monofont: "Fira Mono"



