project:
  type: website
  output-dir: docs # to publish website on GithubPages
# --- By default, all valid Quarto input files (.qmd, .ipynb, .md, .Rmd)
#  will be rendered (NO .file, _dir/)
  render:
    - "*.qmd"
    - "!-secret/"

execute:
  freeze: auto  # Re-render only when source changes

website:
  title: "Idee per Pavia"
  site-url: https://ideeperpavia.com # https://lulliter.github.io/ideeperpavia #"https://github.com/Lulliter/ideexpavia"
  favicon: images/icons8-walking-bridge-32.png
  search: false # no magnifier on navbar
  # Account Google Mktg "Lulliter github (UA-128632724)" collegato a luisamimmi.org
  google-analytics: "G-D5JGRQXE99"

  page-footer:
    left: |
      {{< fa regular copyright >}} Servizio per la pastorale sociale della Diocesi di Pavia 2024
# right: |
#   Pastorale sociale e del lavoro
# Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)

  navbar:
    pinned: true
    # background: "#77221b" # "#72aed8" # "#b78a92" #  "#0084e6" "#EE6A24"
    right:
      - text: "{{< fa regular house >}}"
      # - icon: house-fill # https://icons.getbootstrap.com/?q=home
        href: index.qmd
      - text: "Chi siamo"
        icon: people-fill # https://icons.getbootstrap.com/?q=home
        href: noi.qmd
      - text: "Domande 25 Maggio"
        icon: chat-square-text-fill #  archive-fill # https://icons.getbootstrap.com/?q=home
        href: domande.qmd
format:
  html:
    toc: true
    toc-location: "left"
    code-link: true
    # anchor-sections: true
    # fig-cap-location: margin
    # reference-location: margin
    footnotes-hover: true
    fontsize: 1em
    theme: theme/diocesi.scss
    # css: theme/styles.css
    ##----- code highlighting style
    highlight-style: monokai # atom-one # github # dracula
    mainfont: "Lato"
    monofont: "Fira Mono"
#  html:
    grid:
      body-width: 2000px
      sidebar-width: 0px # non mi serve perche non c'e'
      margin-width: 300px

